### ISSUE TITLE
Reading from stdin does not work, but from file does

### ISSUE THREAD

**Issue by Chaz6** [beschulz/wav2png#19]
This gives the output as expected:-

$ ffmpeg -i Zombies_Ate_My_Neighbors_Panic_of_the_Undead_OC_ReMix.mp3 -acodec pcm_u8 -ar 22050 Zombies_Ate_My_Neighbors_Panic_of_the_Undead_OC_ReMix.wav
$ wav2png --foreground-color=ffb400aa --background-color=2e4562ff Zombies_Ate_My_Neighbors_Panic_of_the_Undead_OC_ReMix.wav -o Zombies_Ate_My_Neighbors_Panic_of_the_Undead_OC_ReMix.mp3.png

However this results in an image that is completely blank:-
$ ffmpeg -i Zombies_Ate_My_Neighbors_Panic_of_the_Undead_OC_ReMix.mp3 -acodec pcm_u8 -ar 22050 -f wav - | wav2png -o Zombies_Ate_My_Neighbors_Panic_of_the_Undead_OC_ReMix.mp3.png /dev/stdin

wav2png does not give any error for either command.

**Comment by beschulz** [comment]
Hmm, weirdly it "Works for me TM".
what I did was 
´´´cat test.wav|wav2png -o test.png /dev/stdin´´´

**Comment by jpeacock** [comment]
I had a similar experience that might help people. I was piping the output out of lame on OSX 10.10.2 and only generated an image that had a tiny bit of waveform data. What turned out happening is that lame was only piping/buffering the first 4096 bytes of an audio file. I ended up creating a temp file using lame, then processing it with wav2png. Still one line on the command line, but took a while to figure out. Seems that ffmpeg uses lame, that would likely be the reason for this too.
