### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by mikevarela** [beschulz/wav2png#27]
Ben,

Hi, forgive the newness. I've downloaded your wav2png program. I've installed homebrew and had some linking issues with libsndfile and boost linking to /usr/local/lib

but overall, is there a way to do a demonstration of the download and build process. I'd love to use your app but I'm not a programmer with compiling experience. And, the droplet keeps failing when trying to open it.

**Comment by mikevarela** [comment]
Also, when trying to build i keep getting an error on a file that's supposed to be included

1 error generated.
In file included from ../src/wav2png.cpp:1:
../src/wav2png.hpp:1:10: fatal error: 'sndfile.hh' file not found
#include <sndfile.hh>

**Comment by beschulz** [comment]
Hi,

I have not looked at the xcode project for quite some time, so it was pretty outdated. I made a release with downloadable binaries so that you get have a look: https://github.com/beschulz/wav2png/releases/tag/0.3

It should be possible now to compile the Xcode project again by doing:
```
cd build
make install_dependencies
open macosx/wav2png.xcodeproj
```

or just download the Droplet linked above if you are in a hurry.

Best,
Ben
